import { Store } from "vuex";

const createStore = () => {
  return new Store({
    state: {
      Products: [
        {
          id: 1329,
          ecom_name: "1",
          product_thambnail:
            "https://bppshops.com/upload/products/thambnail/1734523914538853.webp",
          product_code: "#3R74Q6",
          supplier_id: "120",
          brand_id: "488",
          category_id: "63",
          sub_category_id: "80",
          product_name: "Red color electric tasbih 2",
          product_slug_name: "red-color-electric-tasbih-2",
          product_qty: "0",
          unit_price: "20.00",
          purchase_price: "0.00",
          selling_price: "30.00",
          discount_price: "0.00",
          purchase_date: "2022-06-02",
          status: "1",
          purchase_qty: null,
          product_tags: "Red",
          refundable: "0",
          product_descp: "<p>Red color electric tasbih1</p>",
          meta_title: "Red color electric tasbih",
          meta_desc: "Red color electric tasbih",
          shipping: "1",
          shipping_fee: null,
          cash_on_delivery: "0",
          hot_deals: "1",
          featured: "1",
          special_offer: "1",
          special_deals: "1",
          product_views: "0",
          vat: "0.00",
        },
        {
          id: 1328,
          ecom_name: "1",
          product_thambnail:
            "https://bppshops.com/upload/products/thambnail/1734523825617115.webp",
          product_code: "#F2HKOF",
          supplier_id: "120",
          brand_id: "488",
          category_id: "63",
          sub_category_id: "80",
          product_name: "Premium Green Color tasbih",
          product_slug_name: "premium-green-color-tasbih",
          product_qty: "0",
          unit_price: "50.00",
          purchase_price: "0.00",
          selling_price: "60.00",
          discount_price: "0.00",
          purchase_date: "2022-06-02",
          status: "1",
          purchase_qty: null,
          product_tags: "Premium",
          refundable: "0",
          product_descp: "<p>Premium Green Color tasbih</p>",
          meta_title: "Premium Green Color tasbih",
          meta_desc: "Premium Green Color tasbih",
          shipping: "0",
          shipping_fee: null,
          cash_on_delivery: "0",
          hot_deals: "1",
          featured: "1",
          special_offer: "1",
          special_deals: "1",
          product_views: "0",
          vat: "0.00",
        },
        {
          id: 1327,
          ecom_name: "1",
          product_thambnail:
            "https://bppshops.com/upload/products/thambnail/1734523736205960.webp",
          product_code: "#8KO0ZI",
          supplier_id: "120",
          brand_id: "488",
          category_id: "63",
          sub_category_id: "80",
          product_name: "Premium Golden color tasbih",
          product_slug_name: "premium-golden-color-tasbih",
          product_qty: "10",
          unit_price: "50.00",
          purchase_price: "500.00",
          selling_price: "70.00",
          discount_price: "0.00",
          purchase_date: "2022-06-02",
          status: "1",
          purchase_qty: null,
          product_tags: "Premium",
          refundable: "0",
          product_descp: "<p>Premium Golden color tasbih</p>",
          meta_title: "Premium Golden color tasbih",
          meta_desc: "Premium Golden color tasbih",
          shipping: "1",
          shipping_fee: null,
          cash_on_delivery: "0",
          hot_deals: "1",
          featured: "1",
          special_offer: "1",
          special_deals: "1",
          product_views: "0",
          vat: "0.00",
        },
        {
          id: 1326,
          ecom_name: "1",
          product_thambnail:
            "https://bppshops.com/upload/products/thambnail/1734523656258671.webp",
          product_code: "#O8MAVQ",
          supplier_id: "120",
          brand_id: "488",
          category_id: "63",
          sub_category_id: "80",
          product_name: "Premium Golden and white tasbih",
          product_slug_name: "premium-golden-and-white-tasbih",
          product_qty: "0",
          unit_price: "20.00",
          purchase_price: "0.00",
          selling_price: "30.00",
          discount_price: "0.00",
          purchase_date: "2022-06-02",
          status: "1",
          purchase_qty: null,
          product_tags: "Premium",
          refundable: "0",
          product_descp: "<p>Premium Golden and white tasbih</p>",
          meta_title: "Premium Golden and white tasbih",
          meta_desc: "Premium Golden and white tasbih",
          shipping: "0",
          shipping_fee: null,
          cash_on_delivery: "0",
          hot_deals: "1",
          featured: "1",
          special_offer: "1",
          special_deals: "1",
          product_views: "0",
          vat: "0.00",
        },
        {
          id: 1319,
          ecom_name: "1",
          product_thambnail:
            "https://bppshops.com/upload/products/thambnail/1734523450160403.webp",
          product_code: "#5QF42P",
          supplier_id: "74",
          brand_id: "488",
          category_id: "63",
          sub_category_id: "80",
          product_name: "Premium Colorful tasbih",
          product_slug_name: "premium-colorful-tasbih",
          product_qty: "100",
          unit_price: "60.00",
          purchase_price: "6000.00",
          selling_price: "70.00",
          discount_price: "0.00",
          purchase_date: "2022-06-02",
          status: "1",
          purchase_qty: "100",
          product_tags: "Premium Colorful tasbih",
          refundable: "0",
          product_descp: "<p>Premium Colorful tasbih</p>",
          meta_title: "Premium Colorful tasbih",
          meta_desc: "Premium Colorful tasbih",
          shipping: "0",
          shipping_fee: null,
          cash_on_delivery: "0",
          hot_deals: "1",
          featured: "1",
          special_offer: "1",
          special_deals: "1",
          product_views: "0",
          vat: "0.00",
        },
        {
          id: 1315,
          ecom_name: "1",
          product_thambnail:
            "https://bppshops.com/upload/products/thambnail/1734523261091894.webp",
          product_code: "#56LB5Q",
          supplier_id: "74",
          brand_id: "488",
          category_id: "63",
          sub_category_id: "80",
          product_name: "Premium blue and white color tasbih",
          product_slug_name: "premium-blue-and-white-color-tasbih",
          product_qty: "100",
          unit_price: "20.00",
          purchase_price: "2000.00",
          selling_price: "30.00",
          discount_price: "0.00",
          purchase_date: "2022-06-02",
          status: "1",
          purchase_qty: "100",
          product_tags: "Premium blue and white color tasbih",
          refundable: "1",
          product_descp: "<p>Premium blue and white color tasbih</p>",
          meta_title: "Premium blue and white color tasbih",
          meta_desc: "Premium blue and white color tasbih",
          shipping: "1",
          shipping_fee: null,
          cash_on_delivery: "1",
          hot_deals: "1",
          featured: "1",
          special_offer: "1",
          special_deals: "1",
          product_views: "0",
          vat: "0.00",
        },
        {
          id: 1313,
          ecom_name: "1",
          product_thambnail:
            "https://bppshops.com/upload/products/thambnail/1734523252754999.webp",
          product_code: "#261NN5",
          supplier_id: "74",
          brand_id: "488",
          category_id: "63",
          sub_category_id: "83",
          product_name: "Alhuda Meswak",
          product_slug_name: "alhuda-meswak",
          product_qty: "100",
          unit_price: "12.50",
          purchase_price: "1250.00",
          selling_price: "25.00",
          discount_price: "0.00",
          purchase_date: "2022-06-02",
          status: "1",
          purchase_qty: "100",
          product_tags: "Meswak",
          refundable: "1",
          product_descp: "<p>Meswak</p>",
          meta_title: "Meswak",
          meta_desc: "Meswak",
          shipping: "1",
          shipping_fee: null,
          cash_on_delivery: "1",
          hot_deals: "1",
          featured: "1",
          special_offer: "1",
          special_deals: "1",
          product_views: "1",
          vat: "0.00",
        },
      ],
    },
    mutations: {},
    getters: {},
    actions: {},
  });
};
export default createStore;
